'use strict';
const express=require('express');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
const router=express.Router();
const auth=require('../middleware/authMiddleware');
const {allowRoles}=require('../middleware/roleMiddleware');
const controller=require('../controllers/warrantController');
const roles=['admin','court','court_admin','court_clerk','judge','prosecutor','prosecutor_liaison','officer','cid','cid_director','cid_supervisor','cid_officer','district_admin','district_commander','police_station_commander'];
const dir=path.join(__dirname,'../../uploads/warrants');fs.mkdirSync(dir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:dir,filename:(req,file,cb)=>cb(null,`${Date.now()}-${path.basename(file.originalname).replace(/[^a-zA-Z0-9._-]/g,'_')}`)}),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,file.mimetype==='application/pdf'||file.mimetype.startsWith('image/'))});
router.use(auth);
router.get('/',allowRoles(...roles),controller.list);
router.get('/:id/document',allowRoles(...roles),controller.document);
router.get('/:id',allowRoles(...roles),controller.getOne);
router.post('/',allowRoles(...roles),upload.single('attachment'),controller.create);
router.put('/:id',allowRoles(...roles),controller.update);
router.patch('/:id/:action(cancel|execute)',allowRoles(...roles),controller.updateStatus);
module.exports=router;
