'use strict';
const express=require('express');
const multer=require('multer');
const path=require('path');
const fs=require('fs');
const router=express.Router();
const auth=require('../middleware/authMiddleware');
const {requirePermission}=require('../middleware/permissionMiddleware');
const controller=require('../controllers/warrantController');
const dir=path.join(__dirname,'../../uploads/warrants');fs.mkdirSync(dir,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:dir,filename:(req,file,cb)=>cb(null,`${Date.now()}-${path.basename(file.originalname).replace(/[^a-zA-Z0-9._-]/g,'_')}`)}),limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>cb(null,file.mimetype==='application/pdf'||file.mimetype.startsWith('image/'))});
router.use(auth);
router.get('/',requirePermission('warrants.view'),controller.list);
router.get('/ob-options',requirePermission('warrants.create'),controller.obOptions);
router.get('/:id/document',requirePermission('warrants.print'),controller.document);
router.get('/:id',requirePermission('warrants.view'),controller.getOne);
router.post('/',requirePermission('warrants.create'),upload.single('attachment'),controller.create);
router.put('/:id',requirePermission('warrants.update'),controller.update);
router.patch('/:id/cancel',requirePermission('warrants.cancel'),controller.updateStatus);
router.patch('/:id/execute',requirePermission('warrants.execute'),controller.updateStatus);
module.exports=router;
