'use client';
import { useCallback,useEffect,useState } from 'react';
import { App,Button,Card,DatePicker,Form,Input,Modal,Select,Space,Table,Tag,Typography } from 'antd';
import dayjs from 'dayjs';
import ProtectedRoute from '@/components/auth/ProtectedRoute';
import api from '@/services/api';
const roles=['admin','court','court_admin','court_clerk','judge','prosecutor','prosecutor_liaison','officer','cid','cid_director','cid_supervisor','cid_officer','district_admin','district_commander','police_station_commander'];
const types=[['arrest','Arrest Warrant'],['search','Search Warrant'],['court_summons','Court Summons'],['detention','Detention Warrant'],['other_court_order','Other Court Order']].map(([value,label])=>({value,label}));
export default function WarrantsPage(){
 const {message}=App.useApp();const [rows,setRows]=useState([]);const [loading,setLoading]=useState(true);const [open,setOpen]=useState(false);const [judges,setJudges]=useState([]);const [filter,setFilter]=useState({});const [form]=Form.useForm();
 const load=useCallback(async()=>{setLoading(true);try{const [{data:w},{data:j}]=await Promise.all([api.get('/warrants',{params:filter}),api.get('/legal-personnel/options',{params:{type:'judge'}})]);setRows(w.data||[]);setJudges(j.data||[]);}catch(e){message.error(e.response?.data?.message||'Warrants could not be loaded.');}finally{setLoading(false);}},[filter,message]);useEffect(()=>{load();},[load]);
 const create=async()=>{try{const v=await form.validateFields();const payload={...v,issue_date:v.issue_date.format('YYYY-MM-DD'),expiry_date:v.expiry_date.format('YYYY-MM-DD')};await api.post('/warrants',payload);message.success('Warrant created.');setOpen(false);form.resetFields();load();}catch(e){if(e.response)message.error(e.response?.data?.message||'Create failed.');}};
 const printDocument=async(id)=>{try{const {data}=await api.get(`/warrants/${id}/document`,{responseType:'blob'});const url=URL.createObjectURL(data);const win=window.open(url,'_blank');if(!win)message.warning('Allow pop-ups to print the warrant.');setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){message.error(e.response?.data?.message||'Document download failed.');}};
 const action=async(id,name)=>{try{const body=name==='cancel'?{reason:'Cancelled by authorized user'}:{execution_date:dayjs().format('YYYY-MM-DD'),execution_notes:'Executed'};await api.patch(`/warrants/${id}/${name}`,body);message.success(`Warrant ${name}d.`);load();}catch(e){message.error(e.response?.data?.message||'Action failed.');}};
 return <ProtectedRoute allowedRoles={roles}><Card title={<Typography.Title level={3}>Warrant Management</Typography.Title>} extra={<Button type="primary" onClick={()=>{form.setFieldsValue({status:'draft',issue_date:dayjs()});setOpen(true);}}>Create Warrant</Button>}>
 <Space wrap style={{marginBottom:16}}><Select allowClear placeholder="Status" style={{width:160}} options={['draft','pending','issued','executed','expired','cancelled'].map(v=>({value:v,label:v}))} onChange={v=>setFilter(f=>({...f,status:v}))}/><Select allowClear placeholder="Type" style={{width:190}} options={types} onChange={v=>setFilter(f=>({...f,type:v}))}/><Input.Search allowClear placeholder="Case / OB number" onSearch={v=>setFilter(f=>({...f,case_number:v}))}/></Space>
 <Table rowKey="id" loading={loading} dataSource={rows} pagination={{pageSize:20}} locale={{emptyText:'No warrants found.'}} columns={[{title:'Warrant #',dataIndex:'warrant_number'},{title:'Type',dataIndex:'warrant_type'},{title:'Case / OB',render:(_,r)=>r.case_number||r.ob_number},{title:'Subject',dataIndex:'suspect_name'},{title:'Judge',dataIndex:'judge_name'},{title:'Station',dataIndex:'police_station'},{title:'Issue Date',dataIndex:'issue_date',render:v=>String(v).slice(0,10)},{title:'Expiry',dataIndex:'expiry_date',render:v=>String(v).slice(0,10)},{title:'Status',dataIndex:'status',render:v=><Tag color={v==='executed'?'green':v==='expired'||v==='cancelled'?'red':'blue'}>{v}</Tag>},{title:'Actions',render:(_,r)=><Space><Button onClick={()=>printDocument(r.id)}>Print</Button>{['issued','pending'].includes(r.status)&&<Button onClick={()=>action(r.id,'execute')}>Execute</Button>}{!['executed','cancelled'].includes(r.status)&&<Button danger onClick={()=>action(r.id,'cancel')}>Cancel</Button>}</Space>} ]}/>
 <Modal title="Create Warrant" open={open} onCancel={()=>setOpen(false)} onOk={create}><Form form={form} layout="vertical"><Form.Item name="warrant_number" label="Warrant Number" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="warrant_type" label="Warrant Type" rules={[{required:true}]}><Select options={types}/></Form.Item><Form.Item name="case_id" label="Case ID"><Input type="number" min={1}/></Form.Item><Form.Item name="ob_entry_id" label="OB Entry ID"><Input type="number" min={1}/></Form.Item><Form.Item name="subject_name" label="Suspect / Subject" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="reason" label="Reason" rules={[{required:true}]}><Input.TextArea rows={3}/></Form.Item><Form.Item name="issued_by_judge_id" label="Issued By Judge"><Select allowClear showSearch optionFilterProp="label" options={judges}/></Form.Item><Form.Item name="police_station_id" label="Police Station ID" tooltip="Station-scoped users automatically use their assigned station."><Input type="number" min={1}/></Form.Item><Space><Form.Item name="issue_date" label="Issue Date" rules={[{required:true}]}><DatePicker maxDate={dayjs()}/></Form.Item><Form.Item name="expiry_date" label="Expiry Date" dependencies={['issue_date']} rules={[{required:true},{validator:(_,v)=>!v||!form.getFieldValue('issue_date')||v.isAfter(form.getFieldValue('issue_date'))?Promise.resolve():Promise.reject(new Error('Expiry date must be later than the warrant issue date.'))}]}><DatePicker/></Form.Item></Space><Form.Item name="status" label="Status"><Select options={['draft','pending','issued'].map(v=>({value:v,label:v}))}/></Form.Item></Form></Modal>
 </Card></ProtectedRoute>;
}
